### ISSUE TITLE
Handbook

### ISSUE THREAD

**Issue by tangjeff0** [athensresearch/handbook#23]
The Athens Research handbook is the central repository for how we run the Athens project. This github issue is a collection of tasks and the comments section can be used for general feedback and suggestions.

### Links
- [Handbook (gitbook)](https://athensresearch.gitbook.io/handbook/)
- [Handbook (github .md files)](https://github.com/athensresearch/handbook)
- [Handbook page in our public Roam database](https://roamresearch.com/#/app/athensresearch/page/hv3YOvFbt)

# Tasks
Priority Levels
- P1: high priority
- P2: medium priority
- P3: low priority

## P1
- [x] MVP contributing documentation.md (great reference https://learn.netdata.cloud/contribute/documentation) https://app.gitbook.com/@athensresearch/s/handbook/contributing-1/contributing-documentation
- [x] MVP organizations scheme

## P2
- [X] migrate to gitbook
- [x] migrate [clojurefam docs/resources](https://github.com/athensresearch/ClojureFam) into handbook
- [x] Centralize all documentation -> Migrate ClojureFam / School of Athens docs to here and archive ClojureFam
- [x] Athens gold color hard to read on white background *changed to athens blue
- [x] create an ARCHITECTURE.md athensresearch/athens#765 
- [x] https://app.gitbook.com/@athensresearch/s/handbook/contributing-1/contributing-documentation make the contribution process for github more clear for those unfamiliar with github (more or less akin to Joel's description https://learn.netdata.cloud/contribute/documentation feel free to take this one Joel xD)
- [ ] link github section of contributing documentation to intro to github guide in our docs

## P3
- [ ] adding pages (FAQs, Onboarding)
  - [ ] 
- [ ] filling out empty pages
  - [ ]   
- [ ] outdated pages that need updating
  - [ ] 
- [x] add logo, change brand colors
- [x] figure out glossary.md https://gitbookio.gitbooks.io/documentation/content/format/glossary.html *glossary not possible
- [ ] add section like this: https://open-science-training-handbook.gitbook.io/book/#help-us-making-the-handbook-better

Notes
- alternative documentation tools to consider:
  - https://docusaurus.io/docs/
  - https://mdxjs.com/
- might want to update title of this issue to "Documentation" to encompass handbook as well as documentation within the code
